image: docker:stable

variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2

services:
    - docker:dind

stages:
    - Build image & Push to Registery
    
docker build:
    stage: Build image & Push to Registery
    only:
        - master
    script:
        - docker build -t notes .
        - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin https://dk.dane5hvar.com/v2/
        - docker image ls
        - docker container ls -a
        - docker tag notes dk.dane5hvar.com/v2/notes
        - docker push dk.dane5hvar.com/v2/notes
